---

vars:
  name: arvind
  place: Karur
  
steps:
  - plugin: file
    config:
       path: /Users/kbarvind/Documents/Work/Lab1
       state: create
       mode: folder
       
  - plugin: aptget
    config:
       package: apache2
       state: install
       
  - plugin: service
    config:
       service: apache2
       action: start
   